### ISSUE TITLE
Transition breaks if child components use dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by rmales** [developit/preact-css-transition-group#3] opened 2016-12-02 17:52 UTC
Hi,

It seems like if a child of the transition group uses dangerouslySetInnerHTML it breaks the transition, in the example below the exiting (and then entering) element is removed unexpectedly.
Example: http://jsfiddle.net/28ckgyzj/9/
Compare React: https://jsfiddle.net/rz6uk3pa/3/

Thanks

**Comment by developit** [comment] 2016-12-02 18:03
Hi there,

This works in preact 7, I would recommend using it. `npm i -S preact@beta`.

http://jsfiddle.net/developit/c87fw8zu/

**Comment by developit** [comment] 2016-12-02 18:03
Closing since it's fixed but feel free to ask questions!

**Closed as completed by developit** 2016-12-02 18:03 UTC

**Comment by rmales** [comment] 2016-12-02 18:23
Ah, I should've checked that. Thanks!

**Comment by kilpatty** [comment] 2016-12-23 19:46
Hmm not sure if this is the correct issue, but I'm currently getting this with preact 7.1: 
`Uncaught (in promise) DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided ('[object Object]-enter') contains HTML space characters, which are not valid in tokens.`

**Comment by developit** [comment] 2016-12-23 20:51
Hmm - @Skilgarriff seems like you're passing an Object value for the `name` prop instead of a String.

**Comment by kilpatty** [comment] 2016-12-23 21:11
I'm presuming this is the classname I'm importing using css modules? Getting some very strange behavior from this plugin -> rendering only some of the elements depending on how I get to it.

Edit: Here is the code that currently exists
```
<ReactCSSTransitionGroup
    transitionName={{
      enter: styles.enter,
      enterActive: styles.enterActive,
      leave: styles.leave,
      leaveActive: styles.leaveActive,
    }}
    transitionEnterTimeout={200}
    transitionLeaveTimeout={200}
>
     {this.state.modalOpen ? <NavigationModal onClick={this.closeModal} /> : null}
</ReactCSSTransitionGroup>
```

**Comment by developit** [comment] 2016-12-23 21:15
It's possible yeah - are you able to give a snippet of how you're working with `<CSSTransitionGroup>`?

**Comment by kilpatty** [comment] 2016-12-23 21:16
Just updated the above comment

**Comment by kilpatty** [comment] 2016-12-23 21:31
Just as an update to this -> inside of my NavigationModal, i noticed that only one link was rendering. 

This link is generated using ReactGA.Outbound link, where I am seeing the failing error is when rending of react router v4 "Link" component is attempted to render.

**Comment by developit** [comment] 2016-12-23 22:28
The object notation for `transitionName` is not supported:
https://github.com/developit/preact-css-transition-group/blob/master/src/CSSTransitionGroupChild.js#L24

Open to PRs for it (I think it'd just be a matter of backporting from the React source), but I actually don't use this library so it's a little foreign to me.

**Comment by kilpatty** [comment] 2016-12-23 23:21
Ah great, I'll take a look and see if I can implement it!

**Comment by rmales** [comment] 2017-01-23 16:13
@developit Unfortunately, I think this bug is present again with Preact 7.2, see the JSFiddle from your initial reply: http://jsfiddle.net/developit/c87fw8zu/

**Comment by developit** [comment] 2017-01-23 16:28
Thanks @rmales, seems like [this commit](https://github.com/developit/preact/commit/123978c108579f147c49906c31301ad1712926be) would be the likely cause. I think the issue is more with `preact` than `preact-css-transition-group`.

**Comment by rmales** [comment] 2017-02-06 18:27
@developit Is there a Preact issue that covers this problem?

**Comment by developit** [comment] 2017-02-06 19:43
not that I know of.  Should file one, I lost track of this :(
